source 'https://rubygems.org'

gem 'capybara'
gem 'chromedriver-helper'
gem 'cucumber', '6.1.0'
gem 'ffi'
gem 'pry'
gem 'racc'
gem 'report_builder'
gem 'rspec', '3.10'
gem 'selenium-webdriver', '3.142.7'
